version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2

    working_directory: ~/app
    environment:
      IMAGE_NAME: bnohad/docker-angular-cli
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build docker image $IMAGE_NAME
          command: |
            docker build -t "$IMAGE_NAME" .

      - run:
          name: Upload to docker hub
          command: |
            docker tag $IMAGE_NAME $IMAGE_NAME:$CIRCLE_BUILD_NUM
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $IMAGE_NAME

