version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/app
    environment:
      IMAGE_NAME: bnohad/docker-angular-cli
    steps:
      - checkout

      - run:
          name: Build docker image $IMAGE_NAME
          command: |
            docker build -t $IMAGE_NAME

      - run:
          name: Upload to docker hub
          command: |
            docker tag $IMAGE_NAME $IMAGE_NAME:$CIRCLE_BUILD_NUM
            docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            docker push $IMAGE_NAME

